name: Helm 101
host: localhost:5432
user: user1
password: secret
longText: Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.
resources:
  requests:
    cpu: 5
    memory: 5Gi
  limits:
    cpu: 10
    memory: 10Gi